### PR TITLE
Enable New 3ds CPU Max (804Mhz) as default for CIA build

### PR DESCRIPTION
**Pull request by idgrepthat**
Makerom has been just been updated to allow new3ds CPU speed.
https://github.com/profi200/Project_CTR
I've included the Windows 64 and Linux Builds here.

The only other change needed is the additional line in the cia .rsf.

This has already been used for various libretro emu's.
https://github.com/libretro/RetroArch/commit/db37a2100c8fcb817c3ae3f0eda8b5790b92937e

### CODE REVIEW

**Comment by Steveice10** [comment]
Can you see if this would work in the 3DS RSF as well? If not I can do so later today when I'm free.

**Comment by idgrepthat** [comment]
My initial test gave a card-removed blackscreen error.

**Comment by Steveice10** [comment]
Alright. What you have now looks fine to me, so I'll go ahead and pull it.

Going to leave myself a little to-do here: Update the Mac build of makerom and look into increased CPU speeds via .3DS files.

**Comment by idgrepthat** [comment]
Thanks.
It'd probably also be a good idea to have the CpuSpeed adjustable in the template's appInfo file if that's possible. You never know if extra clock can cause unpredictable behavior or if battery life might be a concern to some devs.

**Comment by idgrepthat** [comment]
It appears there's only standard (268) and full (804) speed for new3ds hardcoded in makerom
https://github.com/profi200/Project_CTR/blob/4ef27aca30a1627a2a031f5126ba1ea578039c0c/makerom/exheader.c#L324
Too bad it's not integer adjustable. Seeing the 3ds running at 100mhz would have been amusing.

**Comment by Steveice10** [comment]
If you don't mind, could you test if the latest commit to enable it via .3DS files works? I don't have an N3DS.

**Comment by idgrepthat** [comment]
It works. Great job.

**Comment by Steveice10** [comment]
Thanks for testing. As I suspected was the case, I just had to edit the flag in the descriptor as well.

For .3DS files, just about every flag or service change needs to be reflected in the descriptor. It would be nice if makerom could automatically generate the descriptor from the RSF settings.

**Comment by idgrepthat** [comment]
A quick extra question: should enabling the L2 cache flag improve speed any?

**Comment by Steveice10** [comment]
Possibly. The details of the N3DS extra cache aren't known, other than that it exists and was previously breaking libkhax.

**Pull request merged**
